apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cloudops-app
  name: cloudops-service
spec:
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
  selector:
    app: cloudops-app
  type: NodePort
status:
  loadBalancer: {}
