apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudops-app
  name: cloudops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudops-app
  strategy: {}
  template:
    metadata:
      labels:
        app: cloudops-app
    spec:
      containers:
      - image: anilnodagala/cloudops-app:openshift-v1
        name: cloudops-app
        ports:
        - containerPort: 5000
        resources: {}
status: {}
